replicas: 1
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
    xpack.security.authc.api_key.enabled: true

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3
