apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: tempo
data:
  otel-collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      otlp:
        endpoint: "tempo-distributor.tempo.svc.cluster.local:4317"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]