apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpbin-dep
  name: httpbin-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpbin-dep
    spec:
      containers:
      - image: kennethreitz/httpbin
        name: httpbin
        ports:
        - containerPort: 80
        resources: {}
status: {}
