apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: httpbin-dep
  name: httpbin-dep
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: httpbin-dep
status:
  loadBalancer: {}
