apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ubuntu-dep
  name: ubuntu-dep
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ubuntu-dep
status:
  loadBalancer: {}
