apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-dep
  name: node-dep
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: node-dep
status:
  loadBalancer: {}
